{
 "title": "Ad Moderation Service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[30s])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{status=~\"4..|5..\"}[1m]))\n  /\n  sum(rate(http_requests_total[1m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(prediction_errors_total[1m])",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Prediction Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(prediction_duration_seconds_bucket[1h])))",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(prediction_duration_seconds_bucket[1h])))",
     "legendFormat": "0.95 quantile"
    }
   ]
  },
  {
   "title": "Predictions Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(result) (predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.95 Percentile latency DB queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, operation) (rate(db_query_duration_seconds_bucket[1m])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Average latency DB queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg by (operation) (rate(db_query_duration_seconds_sum[1m]) / rate(db_query_duration_seconds_count[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}